# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-10 03:44
from __future__ import unicode_literals

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0011_auto_20170808_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='receipt_number',
            field=djstripe.fields.StripeCharField(help_text='The transaction number that appears on email receipts sent for this invoice.', max_length=32, null=True),
        ),
    ]
